/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSelectPortalRouteImport } from './routes/_authed/select-portal'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthedTeacherRouteRouteImport } from './routes/_authed/teacher.route'
import { Route as AuthedSuperAdminRouteRouteImport } from './routes/_authed/super-admin.route'
import { Route as AuthedStudentRouteRouteImport } from './routes/_authed/student.route'
import { Route as AuthedSchoolAdminRouteRouteImport } from './routes/_authed/school-admin.route'
import { Route as AuthedParentRouteRouteImport } from './routes/_authed/parent.route'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin.route'
import { Route as AuthedTeacherIndexRouteImport } from './routes/_authed/teacher/index'
import { Route as AuthedSuperAdminIndexRouteImport } from './routes/_authed/super-admin/index'
import { Route as AuthedStudentIndexRouteImport } from './routes/_authed/student/index'
import { Route as AuthedSchoolAdminIndexRouteImport } from './routes/_authed/school-admin/index'
import { Route as AuthedParentIndexRouteImport } from './routes/_authed/parent/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AuthedTeacherScheduleRouteImport } from './routes/_authed/teacher/schedule'
import { Route as AuthedSuperAdminUsersRouteImport } from './routes/_authed/super-admin/users'
import { Route as AuthedSuperAdminTracksRouteImport } from './routes/_authed/super-admin/tracks'
import { Route as AuthedSuperAdminThemeSettingsRouteImport } from './routes/_authed/super-admin/theme-settings'
import { Route as AuthedSuperAdminSubjectsRouteImport } from './routes/_authed/super-admin/subjects'
import { Route as AuthedSuperAdminReportsRouteImport } from './routes/_authed/super-admin/reports'
import { Route as AuthedSuperAdminPeriodsRouteImport } from './routes/_authed/super-admin/periods'
import { Route as AuthedSuperAdminLevelsRouteImport } from './routes/_authed/super-admin/levels'
import { Route as AuthedSuperAdminGeographyRouteImport } from './routes/_authed/super-admin/geography'
import { Route as AuthedSuperAdminCyclesRouteImport } from './routes/_authed/super-admin/cycles'
import { Route as AuthedSuperAdminConfigurationRouteImport } from './routes/_authed/super-admin/configuration'
import { Route as AuthedSuperAdminAssessmentTypesRouteImport } from './routes/_authed/super-admin/assessment-types'
import { Route as AuthedSuperAdminAcademicYearsRouteImport } from './routes/_authed/super-admin/academic-years'
import { Route as AuthedStudentScheduleRouteImport } from './routes/_authed/student/schedule'
import { Route as AuthedStudentReportCardsRouteImport } from './routes/_authed/student/report-cards'
import { Route as AuthedStudentGradesRouteImport } from './routes/_authed/student/grades'
import { Route as AuthedParentChildrenRouteImport } from './routes/_authed/parent/children'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AuthedTeacherGradesIndexRouteImport } from './routes/_authed/teacher/grades/index'
import { Route as AuthedTeacherClassesIndexRouteImport } from './routes/_authed/teacher/classes/index'
import { Route as AuthedSuperAdminSchoolsIndexRouteImport } from './routes/_authed/super-admin/schools/index'
import { Route as AuthedSchoolAdminYearsIndexRouteImport } from './routes/_authed/school-admin/years/index'
import { Route as AuthedSchoolAdminTeachersIndexRouteImport } from './routes/_authed/school-admin/teachers/index'
import { Route as AuthedSchoolAdminStudentsIndexRouteImport } from './routes/_authed/school-admin/students/index'
import { Route as AuthedSchoolAdminScheduleIndexRouteImport } from './routes/_authed/school-admin/schedule/index'
import { Route as AuthedSchoolAdminReportsIndexRouteImport } from './routes/_authed/school-admin/reports/index'
import { Route as AuthedSchoolAdminParentsIndexRouteImport } from './routes/_authed/school-admin/parents/index'
import { Route as AuthedSchoolAdminFinanceIndexRouteImport } from './routes/_authed/school-admin/finance/index'
import { Route as AuthedSchoolAdminClassroomsIndexRouteImport } from './routes/_authed/school-admin/classrooms/index'
import { Route as AuthedSchoolAdminAssessmentsIndexRouteImport } from './routes/_authed/school-admin/assessments/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthedTeacherGradesClassIdRouteImport } from './routes/_authed/teacher/grades/$classId'
import { Route as AuthedTeacherClassesClassIdRouteImport } from './routes/_authed/teacher/classes/$classId'
import { Route as AuthedSuperAdminSchoolsSchoolIdRouteImport } from './routes/_authed/super-admin/schools/$schoolId'
import { Route as AuthedSchoolAdminYearsCreateRouteImport } from './routes/_authed/school-admin/years/create'
import { Route as AuthedSchoolAdminStudentsPreRegisterRouteImport } from './routes/_authed/school-admin/students/pre-register'
import { Route as AuthedSchoolAdminStudentsAssignRouteImport } from './routes/_authed/school-admin/students/assign'
import { Route as AuthedSchoolAdminStudentsStudentIdRouteImport } from './routes/_authed/school-admin/students/$studentId'
import { Route as AuthedSchoolAdminReportsStatisticsRouteImport } from './routes/_authed/school-admin/reports/statistics'
import { Route as AuthedSchoolAdminYearsYearIdIndexRouteImport } from './routes/_authed/school-admin/years/$yearId/index'
import { Route as AuthedSchoolAdminScheduleTimeSlotsIndexRouteImport } from './routes/_authed/school-admin/schedule/time-slots/index'
import { Route as AuthedSchoolAdminReportsTranscriptsIndexRouteImport } from './routes/_authed/school-admin/reports/transcripts/index'
import { Route as AuthedSchoolAdminReportsReportCardsIndexRouteImport } from './routes/_authed/school-admin/reports/report-cards/index'
import { Route as AuthedSchoolAdminYearsYearIdEditRouteImport } from './routes/_authed/school-admin/years/$yearId/edit'
import { Route as AuthedSchoolAdminTeachersTeacherIdWorkloadRouteImport } from './routes/_authed/school-admin/teachers/$teacherId/workload'
import { Route as AuthedSchoolAdminTeachersTeacherIdAssignmentsRouteImport } from './routes/_authed/school-admin/teachers/$teacherId/assignments'
import { Route as AuthedSchoolAdminReportsTranscriptsTranscriptIdRouteImport } from './routes/_authed/school-admin/reports/transcripts/$transcriptId'
import { Route as AuthedSchoolAdminReportsReportCardsCardIdRouteImport } from './routes/_authed/school-admin/reports/report-cards/$cardId'
import { Route as AuthedSchoolAdminAssessmentsAssessmentIdValidateRouteImport } from './routes/_authed/school-admin/assessments/$assessmentId/validate'
import { Route as AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRouteImport } from './routes/_authed/school-admin/assessments/$assessmentId/subjects'
import { Route as AuthedParentChildrenChildIdScheduleRouteImport } from './routes/_authed/parent/children/$childId/schedule'
import { Route as AuthedParentChildrenChildIdReportCardsRouteImport } from './routes/_authed/parent/children/$childId/report-cards'
import { Route as AuthedParentChildrenChildIdGradesRouteImport } from './routes/_authed/parent/children/$childId/grades'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSelectPortalRoute = AuthedSelectPortalRouteImport.update({
  id: '/select-portal',
  path: '/select-portal',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedTeacherRouteRoute = AuthedTeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuperAdminRouteRoute = AuthedSuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudentRouteRoute = AuthedStudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchoolAdminRouteRoute = AuthedSchoolAdminRouteRouteImport.update({
  id: '/school-admin',
  path: '/school-admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentRouteRoute = AuthedParentRouteRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeacherIndexRoute = AuthedTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedTeacherRouteRoute,
} as any)
const AuthedSuperAdminIndexRoute = AuthedSuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSuperAdminRouteRoute,
} as any)
const AuthedStudentIndexRoute = AuthedStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedStudentRouteRoute,
} as any)
const AuthedSchoolAdminIndexRoute = AuthedSchoolAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSchoolAdminRouteRoute,
} as any)
const AuthedParentIndexRoute = AuthedParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedParentRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeacherScheduleRoute = AuthedTeacherScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedTeacherRouteRoute,
} as any)
const AuthedSuperAdminUsersRoute = AuthedSuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedSuperAdminRouteRoute,
} as any)
const AuthedSuperAdminTracksRoute = AuthedSuperAdminTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AuthedSuperAdminRouteRoute,
} as any)
const AuthedSuperAdminThemeSettingsRoute =
  AuthedSuperAdminThemeSettingsRouteImport.update({
    id: '/theme-settings',
    path: '/theme-settings',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedSuperAdminSubjectsRoute =
  AuthedSuperAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedSuperAdminReportsRoute = AuthedSuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedSuperAdminRouteRoute,
} as any)
const AuthedSuperAdminPeriodsRoute = AuthedSuperAdminPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => AuthedSuperAdminRouteRoute,
} as any)
const AuthedSuperAdminLevelsRoute = AuthedSuperAdminLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => AuthedSuperAdminRouteRoute,
} as any)
const AuthedSuperAdminGeographyRoute =
  AuthedSuperAdminGeographyRouteImport.update({
    id: '/geography',
    path: '/geography',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedSuperAdminCyclesRoute = AuthedSuperAdminCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AuthedSuperAdminRouteRoute,
} as any)
const AuthedSuperAdminConfigurationRoute =
  AuthedSuperAdminConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedSuperAdminAssessmentTypesRoute =
  AuthedSuperAdminAssessmentTypesRouteImport.update({
    id: '/assessment-types',
    path: '/assessment-types',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedSuperAdminAcademicYearsRoute =
  AuthedSuperAdminAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedStudentScheduleRoute = AuthedStudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedStudentRouteRoute,
} as any)
const AuthedStudentReportCardsRoute =
  AuthedStudentReportCardsRouteImport.update({
    id: '/report-cards',
    path: '/report-cards',
    getParentRoute: () => AuthedStudentRouteRoute,
  } as any)
const AuthedStudentGradesRoute = AuthedStudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthedStudentRouteRoute,
} as any)
const AuthedParentChildrenRoute = AuthedParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AuthedParentRouteRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeacherGradesIndexRoute =
  AuthedTeacherGradesIndexRouteImport.update({
    id: '/grades/',
    path: '/grades/',
    getParentRoute: () => AuthedTeacherRouteRoute,
  } as any)
const AuthedTeacherClassesIndexRoute =
  AuthedTeacherClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthedTeacherRouteRoute,
  } as any)
const AuthedSuperAdminSchoolsIndexRoute =
  AuthedSuperAdminSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedSchoolAdminYearsIndexRoute =
  AuthedSchoolAdminYearsIndexRouteImport.update({
    id: '/years/',
    path: '/years/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminTeachersIndexRoute =
  AuthedSchoolAdminTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminStudentsIndexRoute =
  AuthedSchoolAdminStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminScheduleIndexRoute =
  AuthedSchoolAdminScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminReportsIndexRoute =
  AuthedSchoolAdminReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminParentsIndexRoute =
  AuthedSchoolAdminParentsIndexRouteImport.update({
    id: '/parents/',
    path: '/parents/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminFinanceIndexRoute =
  AuthedSchoolAdminFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminClassroomsIndexRoute =
  AuthedSchoolAdminClassroomsIndexRouteImport.update({
    id: '/classrooms/',
    path: '/classrooms/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminAssessmentsIndexRoute =
  AuthedSchoolAdminAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeacherGradesClassIdRoute =
  AuthedTeacherGradesClassIdRouteImport.update({
    id: '/grades/$classId',
    path: '/grades/$classId',
    getParentRoute: () => AuthedTeacherRouteRoute,
  } as any)
const AuthedTeacherClassesClassIdRoute =
  AuthedTeacherClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthedTeacherRouteRoute,
  } as any)
const AuthedSuperAdminSchoolsSchoolIdRoute =
  AuthedSuperAdminSchoolsSchoolIdRouteImport.update({
    id: '/schools/$schoolId',
    path: '/schools/$schoolId',
    getParentRoute: () => AuthedSuperAdminRouteRoute,
  } as any)
const AuthedSchoolAdminYearsCreateRoute =
  AuthedSchoolAdminYearsCreateRouteImport.update({
    id: '/years/create',
    path: '/years/create',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminStudentsPreRegisterRoute =
  AuthedSchoolAdminStudentsPreRegisterRouteImport.update({
    id: '/students/pre-register',
    path: '/students/pre-register',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminStudentsAssignRoute =
  AuthedSchoolAdminStudentsAssignRouteImport.update({
    id: '/students/assign',
    path: '/students/assign',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminStudentsStudentIdRoute =
  AuthedSchoolAdminStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminReportsStatisticsRoute =
  AuthedSchoolAdminReportsStatisticsRouteImport.update({
    id: '/reports/statistics',
    path: '/reports/statistics',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminYearsYearIdIndexRoute =
  AuthedSchoolAdminYearsYearIdIndexRouteImport.update({
    id: '/years/$yearId/',
    path: '/years/$yearId/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminScheduleTimeSlotsIndexRoute =
  AuthedSchoolAdminScheduleTimeSlotsIndexRouteImport.update({
    id: '/schedule/time-slots/',
    path: '/schedule/time-slots/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminReportsTranscriptsIndexRoute =
  AuthedSchoolAdminReportsTranscriptsIndexRouteImport.update({
    id: '/reports/transcripts/',
    path: '/reports/transcripts/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminReportsReportCardsIndexRoute =
  AuthedSchoolAdminReportsReportCardsIndexRouteImport.update({
    id: '/reports/report-cards/',
    path: '/reports/report-cards/',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminYearsYearIdEditRoute =
  AuthedSchoolAdminYearsYearIdEditRouteImport.update({
    id: '/years/$yearId/edit',
    path: '/years/$yearId/edit',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminTeachersTeacherIdWorkloadRoute =
  AuthedSchoolAdminTeachersTeacherIdWorkloadRouteImport.update({
    id: '/teachers/$teacherId/workload',
    path: '/teachers/$teacherId/workload',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute =
  AuthedSchoolAdminTeachersTeacherIdAssignmentsRouteImport.update({
    id: '/teachers/$teacherId/assignments',
    path: '/teachers/$teacherId/assignments',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute =
  AuthedSchoolAdminReportsTranscriptsTranscriptIdRouteImport.update({
    id: '/reports/transcripts/$transcriptId',
    path: '/reports/transcripts/$transcriptId',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminReportsReportCardsCardIdRoute =
  AuthedSchoolAdminReportsReportCardsCardIdRouteImport.update({
    id: '/reports/report-cards/$cardId',
    path: '/reports/report-cards/$cardId',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute =
  AuthedSchoolAdminAssessmentsAssessmentIdValidateRouteImport.update({
    id: '/assessments/$assessmentId/validate',
    path: '/assessments/$assessmentId/validate',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute =
  AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRouteImport.update({
    id: '/assessments/$assessmentId/subjects',
    path: '/assessments/$assessmentId/subjects',
    getParentRoute: () => AuthedSchoolAdminRouteRoute,
  } as any)
const AuthedParentChildrenChildIdScheduleRoute =
  AuthedParentChildrenChildIdScheduleRouteImport.update({
    id: '/$childId/schedule',
    path: '/$childId/schedule',
    getParentRoute: () => AuthedParentChildrenRoute,
  } as any)
const AuthedParentChildrenChildIdReportCardsRoute =
  AuthedParentChildrenChildIdReportCardsRouteImport.update({
    id: '/$childId/report-cards',
    path: '/$childId/report-cards',
    getParentRoute: () => AuthedParentChildrenRoute,
  } as any)
const AuthedParentChildrenChildIdGradesRoute =
  AuthedParentChildrenChildIdGradesRouteImport.update({
    id: '/$childId/grades',
    path: '/$childId/grades',
    getParentRoute: () => AuthedParentChildrenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/parent': typeof AuthedParentRouteRouteWithChildren
  '/school-admin': typeof AuthedSchoolAdminRouteRouteWithChildren
  '/student': typeof AuthedStudentRouteRouteWithChildren
  '/super-admin': typeof AuthedSuperAdminRouteRouteWithChildren
  '/teacher': typeof AuthedTeacherRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/select-portal': typeof AuthedSelectPortalRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/parent/children': typeof AuthedParentChildrenRouteWithChildren
  '/student/grades': typeof AuthedStudentGradesRoute
  '/student/report-cards': typeof AuthedStudentReportCardsRoute
  '/student/schedule': typeof AuthedStudentScheduleRoute
  '/super-admin/academic-years': typeof AuthedSuperAdminAcademicYearsRoute
  '/super-admin/assessment-types': typeof AuthedSuperAdminAssessmentTypesRoute
  '/super-admin/configuration': typeof AuthedSuperAdminConfigurationRoute
  '/super-admin/cycles': typeof AuthedSuperAdminCyclesRoute
  '/super-admin/geography': typeof AuthedSuperAdminGeographyRoute
  '/super-admin/levels': typeof AuthedSuperAdminLevelsRoute
  '/super-admin/periods': typeof AuthedSuperAdminPeriodsRoute
  '/super-admin/reports': typeof AuthedSuperAdminReportsRoute
  '/super-admin/subjects': typeof AuthedSuperAdminSubjectsRoute
  '/super-admin/theme-settings': typeof AuthedSuperAdminThemeSettingsRoute
  '/super-admin/tracks': typeof AuthedSuperAdminTracksRoute
  '/super-admin/users': typeof AuthedSuperAdminUsersRoute
  '/teacher/schedule': typeof AuthedTeacherScheduleRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/parent/': typeof AuthedParentIndexRoute
  '/school-admin/': typeof AuthedSchoolAdminIndexRoute
  '/student/': typeof AuthedStudentIndexRoute
  '/super-admin/': typeof AuthedSuperAdminIndexRoute
  '/teacher/': typeof AuthedTeacherIndexRoute
  '/school-admin/reports/statistics': typeof AuthedSchoolAdminReportsStatisticsRoute
  '/school-admin/students/$studentId': typeof AuthedSchoolAdminStudentsStudentIdRoute
  '/school-admin/students/assign': typeof AuthedSchoolAdminStudentsAssignRoute
  '/school-admin/students/pre-register': typeof AuthedSchoolAdminStudentsPreRegisterRoute
  '/school-admin/years/create': typeof AuthedSchoolAdminYearsCreateRoute
  '/super-admin/schools/$schoolId': typeof AuthedSuperAdminSchoolsSchoolIdRoute
  '/teacher/classes/$classId': typeof AuthedTeacherClassesClassIdRoute
  '/teacher/grades/$classId': typeof AuthedTeacherGradesClassIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/school-admin/assessments/': typeof AuthedSchoolAdminAssessmentsIndexRoute
  '/school-admin/classrooms/': typeof AuthedSchoolAdminClassroomsIndexRoute
  '/school-admin/finance/': typeof AuthedSchoolAdminFinanceIndexRoute
  '/school-admin/parents/': typeof AuthedSchoolAdminParentsIndexRoute
  '/school-admin/reports/': typeof AuthedSchoolAdminReportsIndexRoute
  '/school-admin/schedule/': typeof AuthedSchoolAdminScheduleIndexRoute
  '/school-admin/students/': typeof AuthedSchoolAdminStudentsIndexRoute
  '/school-admin/teachers/': typeof AuthedSchoolAdminTeachersIndexRoute
  '/school-admin/years/': typeof AuthedSchoolAdminYearsIndexRoute
  '/super-admin/schools/': typeof AuthedSuperAdminSchoolsIndexRoute
  '/teacher/classes/': typeof AuthedTeacherClassesIndexRoute
  '/teacher/grades/': typeof AuthedTeacherGradesIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/parent/children/$childId/grades': typeof AuthedParentChildrenChildIdGradesRoute
  '/parent/children/$childId/report-cards': typeof AuthedParentChildrenChildIdReportCardsRoute
  '/parent/children/$childId/schedule': typeof AuthedParentChildrenChildIdScheduleRoute
  '/school-admin/assessments/$assessmentId/subjects': typeof AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute
  '/school-admin/assessments/$assessmentId/validate': typeof AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute
  '/school-admin/reports/report-cards/$cardId': typeof AuthedSchoolAdminReportsReportCardsCardIdRoute
  '/school-admin/reports/transcripts/$transcriptId': typeof AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute
  '/school-admin/teachers/$teacherId/assignments': typeof AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute
  '/school-admin/teachers/$teacherId/workload': typeof AuthedSchoolAdminTeachersTeacherIdWorkloadRoute
  '/school-admin/years/$yearId/edit': typeof AuthedSchoolAdminYearsYearIdEditRoute
  '/school-admin/reports/report-cards/': typeof AuthedSchoolAdminReportsReportCardsIndexRoute
  '/school-admin/reports/transcripts/': typeof AuthedSchoolAdminReportsTranscriptsIndexRoute
  '/school-admin/schedule/time-slots/': typeof AuthedSchoolAdminScheduleTimeSlotsIndexRoute
  '/school-admin/years/$yearId/': typeof AuthedSchoolAdminYearsYearIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/select-portal': typeof AuthedSelectPortalRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/parent/children': typeof AuthedParentChildrenRouteWithChildren
  '/student/grades': typeof AuthedStudentGradesRoute
  '/student/report-cards': typeof AuthedStudentReportCardsRoute
  '/student/schedule': typeof AuthedStudentScheduleRoute
  '/super-admin/academic-years': typeof AuthedSuperAdminAcademicYearsRoute
  '/super-admin/assessment-types': typeof AuthedSuperAdminAssessmentTypesRoute
  '/super-admin/configuration': typeof AuthedSuperAdminConfigurationRoute
  '/super-admin/cycles': typeof AuthedSuperAdminCyclesRoute
  '/super-admin/geography': typeof AuthedSuperAdminGeographyRoute
  '/super-admin/levels': typeof AuthedSuperAdminLevelsRoute
  '/super-admin/periods': typeof AuthedSuperAdminPeriodsRoute
  '/super-admin/reports': typeof AuthedSuperAdminReportsRoute
  '/super-admin/subjects': typeof AuthedSuperAdminSubjectsRoute
  '/super-admin/theme-settings': typeof AuthedSuperAdminThemeSettingsRoute
  '/super-admin/tracks': typeof AuthedSuperAdminTracksRoute
  '/super-admin/users': typeof AuthedSuperAdminUsersRoute
  '/teacher/schedule': typeof AuthedTeacherScheduleRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/parent': typeof AuthedParentIndexRoute
  '/school-admin': typeof AuthedSchoolAdminIndexRoute
  '/student': typeof AuthedStudentIndexRoute
  '/super-admin': typeof AuthedSuperAdminIndexRoute
  '/teacher': typeof AuthedTeacherIndexRoute
  '/school-admin/reports/statistics': typeof AuthedSchoolAdminReportsStatisticsRoute
  '/school-admin/students/$studentId': typeof AuthedSchoolAdminStudentsStudentIdRoute
  '/school-admin/students/assign': typeof AuthedSchoolAdminStudentsAssignRoute
  '/school-admin/students/pre-register': typeof AuthedSchoolAdminStudentsPreRegisterRoute
  '/school-admin/years/create': typeof AuthedSchoolAdminYearsCreateRoute
  '/super-admin/schools/$schoolId': typeof AuthedSuperAdminSchoolsSchoolIdRoute
  '/teacher/classes/$classId': typeof AuthedTeacherClassesClassIdRoute
  '/teacher/grades/$classId': typeof AuthedTeacherGradesClassIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/school-admin/assessments': typeof AuthedSchoolAdminAssessmentsIndexRoute
  '/school-admin/classrooms': typeof AuthedSchoolAdminClassroomsIndexRoute
  '/school-admin/finance': typeof AuthedSchoolAdminFinanceIndexRoute
  '/school-admin/parents': typeof AuthedSchoolAdminParentsIndexRoute
  '/school-admin/reports': typeof AuthedSchoolAdminReportsIndexRoute
  '/school-admin/schedule': typeof AuthedSchoolAdminScheduleIndexRoute
  '/school-admin/students': typeof AuthedSchoolAdminStudentsIndexRoute
  '/school-admin/teachers': typeof AuthedSchoolAdminTeachersIndexRoute
  '/school-admin/years': typeof AuthedSchoolAdminYearsIndexRoute
  '/super-admin/schools': typeof AuthedSuperAdminSchoolsIndexRoute
  '/teacher/classes': typeof AuthedTeacherClassesIndexRoute
  '/teacher/grades': typeof AuthedTeacherGradesIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/parent/children/$childId/grades': typeof AuthedParentChildrenChildIdGradesRoute
  '/parent/children/$childId/report-cards': typeof AuthedParentChildrenChildIdReportCardsRoute
  '/parent/children/$childId/schedule': typeof AuthedParentChildrenChildIdScheduleRoute
  '/school-admin/assessments/$assessmentId/subjects': typeof AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute
  '/school-admin/assessments/$assessmentId/validate': typeof AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute
  '/school-admin/reports/report-cards/$cardId': typeof AuthedSchoolAdminReportsReportCardsCardIdRoute
  '/school-admin/reports/transcripts/$transcriptId': typeof AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute
  '/school-admin/teachers/$teacherId/assignments': typeof AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute
  '/school-admin/teachers/$teacherId/workload': typeof AuthedSchoolAdminTeachersTeacherIdWorkloadRoute
  '/school-admin/years/$yearId/edit': typeof AuthedSchoolAdminYearsYearIdEditRoute
  '/school-admin/reports/report-cards': typeof AuthedSchoolAdminReportsReportCardsIndexRoute
  '/school-admin/reports/transcripts': typeof AuthedSchoolAdminReportsTranscriptsIndexRoute
  '/school-admin/schedule/time-slots': typeof AuthedSchoolAdminScheduleTimeSlotsIndexRoute
  '/school-admin/years/$yearId': typeof AuthedSchoolAdminYearsYearIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/parent': typeof AuthedParentRouteRouteWithChildren
  '/_authed/school-admin': typeof AuthedSchoolAdminRouteRouteWithChildren
  '/_authed/student': typeof AuthedStudentRouteRouteWithChildren
  '/_authed/super-admin': typeof AuthedSuperAdminRouteRouteWithChildren
  '/_authed/teacher': typeof AuthedTeacherRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/select-portal': typeof AuthedSelectPortalRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/parent/children': typeof AuthedParentChildrenRouteWithChildren
  '/_authed/student/grades': typeof AuthedStudentGradesRoute
  '/_authed/student/report-cards': typeof AuthedStudentReportCardsRoute
  '/_authed/student/schedule': typeof AuthedStudentScheduleRoute
  '/_authed/super-admin/academic-years': typeof AuthedSuperAdminAcademicYearsRoute
  '/_authed/super-admin/assessment-types': typeof AuthedSuperAdminAssessmentTypesRoute
  '/_authed/super-admin/configuration': typeof AuthedSuperAdminConfigurationRoute
  '/_authed/super-admin/cycles': typeof AuthedSuperAdminCyclesRoute
  '/_authed/super-admin/geography': typeof AuthedSuperAdminGeographyRoute
  '/_authed/super-admin/levels': typeof AuthedSuperAdminLevelsRoute
  '/_authed/super-admin/periods': typeof AuthedSuperAdminPeriodsRoute
  '/_authed/super-admin/reports': typeof AuthedSuperAdminReportsRoute
  '/_authed/super-admin/subjects': typeof AuthedSuperAdminSubjectsRoute
  '/_authed/super-admin/theme-settings': typeof AuthedSuperAdminThemeSettingsRoute
  '/_authed/super-admin/tracks': typeof AuthedSuperAdminTracksRoute
  '/_authed/super-admin/users': typeof AuthedSuperAdminUsersRoute
  '/_authed/teacher/schedule': typeof AuthedTeacherScheduleRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/parent/': typeof AuthedParentIndexRoute
  '/_authed/school-admin/': typeof AuthedSchoolAdminIndexRoute
  '/_authed/student/': typeof AuthedStudentIndexRoute
  '/_authed/super-admin/': typeof AuthedSuperAdminIndexRoute
  '/_authed/teacher/': typeof AuthedTeacherIndexRoute
  '/_authed/school-admin/reports/statistics': typeof AuthedSchoolAdminReportsStatisticsRoute
  '/_authed/school-admin/students/$studentId': typeof AuthedSchoolAdminStudentsStudentIdRoute
  '/_authed/school-admin/students/assign': typeof AuthedSchoolAdminStudentsAssignRoute
  '/_authed/school-admin/students/pre-register': typeof AuthedSchoolAdminStudentsPreRegisterRoute
  '/_authed/school-admin/years/create': typeof AuthedSchoolAdminYearsCreateRoute
  '/_authed/super-admin/schools/$schoolId': typeof AuthedSuperAdminSchoolsSchoolIdRoute
  '/_authed/teacher/classes/$classId': typeof AuthedTeacherClassesClassIdRoute
  '/_authed/teacher/grades/$classId': typeof AuthedTeacherGradesClassIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/_authed/school-admin/assessments/': typeof AuthedSchoolAdminAssessmentsIndexRoute
  '/_authed/school-admin/classrooms/': typeof AuthedSchoolAdminClassroomsIndexRoute
  '/_authed/school-admin/finance/': typeof AuthedSchoolAdminFinanceIndexRoute
  '/_authed/school-admin/parents/': typeof AuthedSchoolAdminParentsIndexRoute
  '/_authed/school-admin/reports/': typeof AuthedSchoolAdminReportsIndexRoute
  '/_authed/school-admin/schedule/': typeof AuthedSchoolAdminScheduleIndexRoute
  '/_authed/school-admin/students/': typeof AuthedSchoolAdminStudentsIndexRoute
  '/_authed/school-admin/teachers/': typeof AuthedSchoolAdminTeachersIndexRoute
  '/_authed/school-admin/years/': typeof AuthedSchoolAdminYearsIndexRoute
  '/_authed/super-admin/schools/': typeof AuthedSuperAdminSchoolsIndexRoute
  '/_authed/teacher/classes/': typeof AuthedTeacherClassesIndexRoute
  '/_authed/teacher/grades/': typeof AuthedTeacherGradesIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/_authed/parent/children/$childId/grades': typeof AuthedParentChildrenChildIdGradesRoute
  '/_authed/parent/children/$childId/report-cards': typeof AuthedParentChildrenChildIdReportCardsRoute
  '/_authed/parent/children/$childId/schedule': typeof AuthedParentChildrenChildIdScheduleRoute
  '/_authed/school-admin/assessments/$assessmentId/subjects': typeof AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute
  '/_authed/school-admin/assessments/$assessmentId/validate': typeof AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute
  '/_authed/school-admin/reports/report-cards/$cardId': typeof AuthedSchoolAdminReportsReportCardsCardIdRoute
  '/_authed/school-admin/reports/transcripts/$transcriptId': typeof AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute
  '/_authed/school-admin/teachers/$teacherId/assignments': typeof AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute
  '/_authed/school-admin/teachers/$teacherId/workload': typeof AuthedSchoolAdminTeachersTeacherIdWorkloadRoute
  '/_authed/school-admin/years/$yearId/edit': typeof AuthedSchoolAdminYearsYearIdEditRoute
  '/_authed/school-admin/reports/report-cards/': typeof AuthedSchoolAdminReportsReportCardsIndexRoute
  '/_authed/school-admin/reports/transcripts/': typeof AuthedSchoolAdminReportsTranscriptsIndexRoute
  '/_authed/school-admin/schedule/time-slots/': typeof AuthedSchoolAdminScheduleTimeSlotsIndexRoute
  '/_authed/school-admin/years/$yearId/': typeof AuthedSchoolAdminYearsYearIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/unauthorized'
    | '/admin'
    | '/parent'
    | '/school-admin'
    | '/student'
    | '/super-admin'
    | '/teacher'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/select-portal'
    | '/admin/users'
    | '/parent/children'
    | '/student/grades'
    | '/student/report-cards'
    | '/student/schedule'
    | '/super-admin/academic-years'
    | '/super-admin/assessment-types'
    | '/super-admin/configuration'
    | '/super-admin/cycles'
    | '/super-admin/geography'
    | '/super-admin/levels'
    | '/super-admin/periods'
    | '/super-admin/reports'
    | '/super-admin/subjects'
    | '/super-admin/theme-settings'
    | '/super-admin/tracks'
    | '/super-admin/users'
    | '/teacher/schedule'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/'
    | '/parent/'
    | '/school-admin/'
    | '/student/'
    | '/super-admin/'
    | '/teacher/'
    | '/school-admin/reports/statistics'
    | '/school-admin/students/$studentId'
    | '/school-admin/students/assign'
    | '/school-admin/students/pre-register'
    | '/school-admin/years/create'
    | '/super-admin/schools/$schoolId'
    | '/teacher/classes/$classId'
    | '/teacher/grades/$classId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/school-admin/assessments/'
    | '/school-admin/classrooms/'
    | '/school-admin/finance/'
    | '/school-admin/parents/'
    | '/school-admin/reports/'
    | '/school-admin/schedule/'
    | '/school-admin/students/'
    | '/school-admin/teachers/'
    | '/school-admin/years/'
    | '/super-admin/schools/'
    | '/teacher/classes/'
    | '/teacher/grades/'
    | '/demo/start/ssr/'
    | '/parent/children/$childId/grades'
    | '/parent/children/$childId/report-cards'
    | '/parent/children/$childId/schedule'
    | '/school-admin/assessments/$assessmentId/subjects'
    | '/school-admin/assessments/$assessmentId/validate'
    | '/school-admin/reports/report-cards/$cardId'
    | '/school-admin/reports/transcripts/$transcriptId'
    | '/school-admin/teachers/$teacherId/assignments'
    | '/school-admin/teachers/$teacherId/workload'
    | '/school-admin/years/$yearId/edit'
    | '/school-admin/reports/report-cards/'
    | '/school-admin/reports/transcripts/'
    | '/school-admin/schedule/time-slots/'
    | '/school-admin/years/$yearId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/select-portal'
    | '/admin/users'
    | '/parent/children'
    | '/student/grades'
    | '/student/report-cards'
    | '/student/schedule'
    | '/super-admin/academic-years'
    | '/super-admin/assessment-types'
    | '/super-admin/configuration'
    | '/super-admin/cycles'
    | '/super-admin/geography'
    | '/super-admin/levels'
    | '/super-admin/periods'
    | '/super-admin/reports'
    | '/super-admin/subjects'
    | '/super-admin/theme-settings'
    | '/super-admin/tracks'
    | '/super-admin/users'
    | '/teacher/schedule'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin'
    | '/parent'
    | '/school-admin'
    | '/student'
    | '/super-admin'
    | '/teacher'
    | '/school-admin/reports/statistics'
    | '/school-admin/students/$studentId'
    | '/school-admin/students/assign'
    | '/school-admin/students/pre-register'
    | '/school-admin/years/create'
    | '/super-admin/schools/$schoolId'
    | '/teacher/classes/$classId'
    | '/teacher/grades/$classId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/school-admin/assessments'
    | '/school-admin/classrooms'
    | '/school-admin/finance'
    | '/school-admin/parents'
    | '/school-admin/reports'
    | '/school-admin/schedule'
    | '/school-admin/students'
    | '/school-admin/teachers'
    | '/school-admin/years'
    | '/super-admin/schools'
    | '/teacher/classes'
    | '/teacher/grades'
    | '/demo/start/ssr'
    | '/parent/children/$childId/grades'
    | '/parent/children/$childId/report-cards'
    | '/parent/children/$childId/schedule'
    | '/school-admin/assessments/$assessmentId/subjects'
    | '/school-admin/assessments/$assessmentId/validate'
    | '/school-admin/reports/report-cards/$cardId'
    | '/school-admin/reports/transcripts/$transcriptId'
    | '/school-admin/teachers/$teacherId/assignments'
    | '/school-admin/teachers/$teacherId/workload'
    | '/school-admin/years/$yearId/edit'
    | '/school-admin/reports/report-cards'
    | '/school-admin/reports/transcripts'
    | '/school-admin/schedule/time-slots'
    | '/school-admin/years/$yearId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/logout'
    | '/unauthorized'
    | '/_authed/admin'
    | '/_authed/parent'
    | '/_authed/school-admin'
    | '/_authed/student'
    | '/_authed/super-admin'
    | '/_authed/teacher'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authed/dashboard'
    | '/_authed/select-portal'
    | '/_authed/admin/users'
    | '/_authed/parent/children'
    | '/_authed/student/grades'
    | '/_authed/student/report-cards'
    | '/_authed/student/schedule'
    | '/_authed/super-admin/academic-years'
    | '/_authed/super-admin/assessment-types'
    | '/_authed/super-admin/configuration'
    | '/_authed/super-admin/cycles'
    | '/_authed/super-admin/geography'
    | '/_authed/super-admin/levels'
    | '/_authed/super-admin/periods'
    | '/_authed/super-admin/reports'
    | '/_authed/super-admin/subjects'
    | '/_authed/super-admin/theme-settings'
    | '/_authed/super-admin/tracks'
    | '/_authed/super-admin/users'
    | '/_authed/teacher/schedule'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authed/admin/'
    | '/_authed/parent/'
    | '/_authed/school-admin/'
    | '/_authed/student/'
    | '/_authed/super-admin/'
    | '/_authed/teacher/'
    | '/_authed/school-admin/reports/statistics'
    | '/_authed/school-admin/students/$studentId'
    | '/_authed/school-admin/students/assign'
    | '/_authed/school-admin/students/pre-register'
    | '/_authed/school-admin/years/create'
    | '/_authed/super-admin/schools/$schoolId'
    | '/_authed/teacher/classes/$classId'
    | '/_authed/teacher/grades/$classId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/_authed/school-admin/assessments/'
    | '/_authed/school-admin/classrooms/'
    | '/_authed/school-admin/finance/'
    | '/_authed/school-admin/parents/'
    | '/_authed/school-admin/reports/'
    | '/_authed/school-admin/schedule/'
    | '/_authed/school-admin/students/'
    | '/_authed/school-admin/teachers/'
    | '/_authed/school-admin/years/'
    | '/_authed/super-admin/schools/'
    | '/_authed/teacher/classes/'
    | '/_authed/teacher/grades/'
    | '/demo/start/ssr/'
    | '/_authed/parent/children/$childId/grades'
    | '/_authed/parent/children/$childId/report-cards'
    | '/_authed/parent/children/$childId/schedule'
    | '/_authed/school-admin/assessments/$assessmentId/subjects'
    | '/_authed/school-admin/assessments/$assessmentId/validate'
    | '/_authed/school-admin/reports/report-cards/$cardId'
    | '/_authed/school-admin/reports/transcripts/$transcriptId'
    | '/_authed/school-admin/teachers/$teacherId/assignments'
    | '/_authed/school-admin/teachers/$teacherId/workload'
    | '/_authed/school-admin/years/$yearId/edit'
    | '/_authed/school-admin/reports/report-cards/'
    | '/_authed/school-admin/reports/transcripts/'
    | '/_authed/school-admin/schedule/time-slots/'
    | '/_authed/school-admin/years/$yearId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/select-portal': {
      id: '/_authed/select-portal'
      path: '/select-portal'
      fullPath: '/select-portal'
      preLoaderRoute: typeof AuthedSelectPortalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/teacher': {
      id: '/_authed/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthedTeacherRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/super-admin': {
      id: '/_authed/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthedSuperAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/student': {
      id: '/_authed/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthedStudentRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/school-admin': {
      id: '/_authed/school-admin'
      path: '/school-admin'
      fullPath: '/school-admin'
      preLoaderRoute: typeof AuthedSchoolAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent': {
      id: '/_authed/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthedParentRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teacher/': {
      id: '/_authed/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthedTeacherIndexRouteImport
      parentRoute: typeof AuthedTeacherRouteRoute
    }
    '/_authed/super-admin/': {
      id: '/_authed/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthedSuperAdminIndexRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/student/': {
      id: '/_authed/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthedStudentIndexRouteImport
      parentRoute: typeof AuthedStudentRouteRoute
    }
    '/_authed/school-admin/': {
      id: '/_authed/school-admin/'
      path: '/'
      fullPath: '/school-admin/'
      preLoaderRoute: typeof AuthedSchoolAdminIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/parent/': {
      id: '/_authed/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthedParentIndexRouteImport
      parentRoute: typeof AuthedParentRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teacher/schedule': {
      id: '/_authed/teacher/schedule'
      path: '/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof AuthedTeacherScheduleRouteImport
      parentRoute: typeof AuthedTeacherRouteRoute
    }
    '/_authed/super-admin/users': {
      id: '/_authed/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthedSuperAdminUsersRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/tracks': {
      id: '/_authed/super-admin/tracks'
      path: '/tracks'
      fullPath: '/super-admin/tracks'
      preLoaderRoute: typeof AuthedSuperAdminTracksRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/theme-settings': {
      id: '/_authed/super-admin/theme-settings'
      path: '/theme-settings'
      fullPath: '/super-admin/theme-settings'
      preLoaderRoute: typeof AuthedSuperAdminThemeSettingsRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/subjects': {
      id: '/_authed/super-admin/subjects'
      path: '/subjects'
      fullPath: '/super-admin/subjects'
      preLoaderRoute: typeof AuthedSuperAdminSubjectsRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/reports': {
      id: '/_authed/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof AuthedSuperAdminReportsRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/periods': {
      id: '/_authed/super-admin/periods'
      path: '/periods'
      fullPath: '/super-admin/periods'
      preLoaderRoute: typeof AuthedSuperAdminPeriodsRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/levels': {
      id: '/_authed/super-admin/levels'
      path: '/levels'
      fullPath: '/super-admin/levels'
      preLoaderRoute: typeof AuthedSuperAdminLevelsRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/geography': {
      id: '/_authed/super-admin/geography'
      path: '/geography'
      fullPath: '/super-admin/geography'
      preLoaderRoute: typeof AuthedSuperAdminGeographyRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/cycles': {
      id: '/_authed/super-admin/cycles'
      path: '/cycles'
      fullPath: '/super-admin/cycles'
      preLoaderRoute: typeof AuthedSuperAdminCyclesRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/configuration': {
      id: '/_authed/super-admin/configuration'
      path: '/configuration'
      fullPath: '/super-admin/configuration'
      preLoaderRoute: typeof AuthedSuperAdminConfigurationRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/assessment-types': {
      id: '/_authed/super-admin/assessment-types'
      path: '/assessment-types'
      fullPath: '/super-admin/assessment-types'
      preLoaderRoute: typeof AuthedSuperAdminAssessmentTypesRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/super-admin/academic-years': {
      id: '/_authed/super-admin/academic-years'
      path: '/academic-years'
      fullPath: '/super-admin/academic-years'
      preLoaderRoute: typeof AuthedSuperAdminAcademicYearsRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/student/schedule': {
      id: '/_authed/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof AuthedStudentScheduleRouteImport
      parentRoute: typeof AuthedStudentRouteRoute
    }
    '/_authed/student/report-cards': {
      id: '/_authed/student/report-cards'
      path: '/report-cards'
      fullPath: '/student/report-cards'
      preLoaderRoute: typeof AuthedStudentReportCardsRouteImport
      parentRoute: typeof AuthedStudentRouteRoute
    }
    '/_authed/student/grades': {
      id: '/_authed/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof AuthedStudentGradesRouteImport
      parentRoute: typeof AuthedStudentRouteRoute
    }
    '/_authed/parent/children': {
      id: '/_authed/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof AuthedParentChildrenRouteImport
      parentRoute: typeof AuthedParentRouteRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teacher/grades/': {
      id: '/_authed/teacher/grades/'
      path: '/grades'
      fullPath: '/teacher/grades/'
      preLoaderRoute: typeof AuthedTeacherGradesIndexRouteImport
      parentRoute: typeof AuthedTeacherRouteRoute
    }
    '/_authed/teacher/classes/': {
      id: '/_authed/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof AuthedTeacherClassesIndexRouteImport
      parentRoute: typeof AuthedTeacherRouteRoute
    }
    '/_authed/super-admin/schools/': {
      id: '/_authed/super-admin/schools/'
      path: '/schools'
      fullPath: '/super-admin/schools/'
      preLoaderRoute: typeof AuthedSuperAdminSchoolsIndexRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/school-admin/years/': {
      id: '/_authed/school-admin/years/'
      path: '/years'
      fullPath: '/school-admin/years/'
      preLoaderRoute: typeof AuthedSchoolAdminYearsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/teachers/': {
      id: '/_authed/school-admin/teachers/'
      path: '/teachers'
      fullPath: '/school-admin/teachers/'
      preLoaderRoute: typeof AuthedSchoolAdminTeachersIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/students/': {
      id: '/_authed/school-admin/students/'
      path: '/students'
      fullPath: '/school-admin/students/'
      preLoaderRoute: typeof AuthedSchoolAdminStudentsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/schedule/': {
      id: '/_authed/school-admin/schedule/'
      path: '/schedule'
      fullPath: '/school-admin/schedule/'
      preLoaderRoute: typeof AuthedSchoolAdminScheduleIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/reports/': {
      id: '/_authed/school-admin/reports/'
      path: '/reports'
      fullPath: '/school-admin/reports/'
      preLoaderRoute: typeof AuthedSchoolAdminReportsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/parents/': {
      id: '/_authed/school-admin/parents/'
      path: '/parents'
      fullPath: '/school-admin/parents/'
      preLoaderRoute: typeof AuthedSchoolAdminParentsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/finance/': {
      id: '/_authed/school-admin/finance/'
      path: '/finance'
      fullPath: '/school-admin/finance/'
      preLoaderRoute: typeof AuthedSchoolAdminFinanceIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/classrooms/': {
      id: '/_authed/school-admin/classrooms/'
      path: '/classrooms'
      fullPath: '/school-admin/classrooms/'
      preLoaderRoute: typeof AuthedSchoolAdminClassroomsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/assessments/': {
      id: '/_authed/school-admin/assessments/'
      path: '/assessments'
      fullPath: '/school-admin/assessments/'
      preLoaderRoute: typeof AuthedSchoolAdminAssessmentsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teacher/grades/$classId': {
      id: '/_authed/teacher/grades/$classId'
      path: '/grades/$classId'
      fullPath: '/teacher/grades/$classId'
      preLoaderRoute: typeof AuthedTeacherGradesClassIdRouteImport
      parentRoute: typeof AuthedTeacherRouteRoute
    }
    '/_authed/teacher/classes/$classId': {
      id: '/_authed/teacher/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof AuthedTeacherClassesClassIdRouteImport
      parentRoute: typeof AuthedTeacherRouteRoute
    }
    '/_authed/super-admin/schools/$schoolId': {
      id: '/_authed/super-admin/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/super-admin/schools/$schoolId'
      preLoaderRoute: typeof AuthedSuperAdminSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthedSuperAdminRouteRoute
    }
    '/_authed/school-admin/years/create': {
      id: '/_authed/school-admin/years/create'
      path: '/years/create'
      fullPath: '/school-admin/years/create'
      preLoaderRoute: typeof AuthedSchoolAdminYearsCreateRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/students/pre-register': {
      id: '/_authed/school-admin/students/pre-register'
      path: '/students/pre-register'
      fullPath: '/school-admin/students/pre-register'
      preLoaderRoute: typeof AuthedSchoolAdminStudentsPreRegisterRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/students/assign': {
      id: '/_authed/school-admin/students/assign'
      path: '/students/assign'
      fullPath: '/school-admin/students/assign'
      preLoaderRoute: typeof AuthedSchoolAdminStudentsAssignRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/students/$studentId': {
      id: '/_authed/school-admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/school-admin/students/$studentId'
      preLoaderRoute: typeof AuthedSchoolAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/reports/statistics': {
      id: '/_authed/school-admin/reports/statistics'
      path: '/reports/statistics'
      fullPath: '/school-admin/reports/statistics'
      preLoaderRoute: typeof AuthedSchoolAdminReportsStatisticsRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/years/$yearId/': {
      id: '/_authed/school-admin/years/$yearId/'
      path: '/years/$yearId'
      fullPath: '/school-admin/years/$yearId/'
      preLoaderRoute: typeof AuthedSchoolAdminYearsYearIdIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/schedule/time-slots/': {
      id: '/_authed/school-admin/schedule/time-slots/'
      path: '/schedule/time-slots'
      fullPath: '/school-admin/schedule/time-slots/'
      preLoaderRoute: typeof AuthedSchoolAdminScheduleTimeSlotsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/reports/transcripts/': {
      id: '/_authed/school-admin/reports/transcripts/'
      path: '/reports/transcripts'
      fullPath: '/school-admin/reports/transcripts/'
      preLoaderRoute: typeof AuthedSchoolAdminReportsTranscriptsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/reports/report-cards/': {
      id: '/_authed/school-admin/reports/report-cards/'
      path: '/reports/report-cards'
      fullPath: '/school-admin/reports/report-cards/'
      preLoaderRoute: typeof AuthedSchoolAdminReportsReportCardsIndexRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/years/$yearId/edit': {
      id: '/_authed/school-admin/years/$yearId/edit'
      path: '/years/$yearId/edit'
      fullPath: '/school-admin/years/$yearId/edit'
      preLoaderRoute: typeof AuthedSchoolAdminYearsYearIdEditRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/teachers/$teacherId/workload': {
      id: '/_authed/school-admin/teachers/$teacherId/workload'
      path: '/teachers/$teacherId/workload'
      fullPath: '/school-admin/teachers/$teacherId/workload'
      preLoaderRoute: typeof AuthedSchoolAdminTeachersTeacherIdWorkloadRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/teachers/$teacherId/assignments': {
      id: '/_authed/school-admin/teachers/$teacherId/assignments'
      path: '/teachers/$teacherId/assignments'
      fullPath: '/school-admin/teachers/$teacherId/assignments'
      preLoaderRoute: typeof AuthedSchoolAdminTeachersTeacherIdAssignmentsRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/reports/transcripts/$transcriptId': {
      id: '/_authed/school-admin/reports/transcripts/$transcriptId'
      path: '/reports/transcripts/$transcriptId'
      fullPath: '/school-admin/reports/transcripts/$transcriptId'
      preLoaderRoute: typeof AuthedSchoolAdminReportsTranscriptsTranscriptIdRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/reports/report-cards/$cardId': {
      id: '/_authed/school-admin/reports/report-cards/$cardId'
      path: '/reports/report-cards/$cardId'
      fullPath: '/school-admin/reports/report-cards/$cardId'
      preLoaderRoute: typeof AuthedSchoolAdminReportsReportCardsCardIdRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/assessments/$assessmentId/validate': {
      id: '/_authed/school-admin/assessments/$assessmentId/validate'
      path: '/assessments/$assessmentId/validate'
      fullPath: '/school-admin/assessments/$assessmentId/validate'
      preLoaderRoute: typeof AuthedSchoolAdminAssessmentsAssessmentIdValidateRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/school-admin/assessments/$assessmentId/subjects': {
      id: '/_authed/school-admin/assessments/$assessmentId/subjects'
      path: '/assessments/$assessmentId/subjects'
      fullPath: '/school-admin/assessments/$assessmentId/subjects'
      preLoaderRoute: typeof AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRouteImport
      parentRoute: typeof AuthedSchoolAdminRouteRoute
    }
    '/_authed/parent/children/$childId/schedule': {
      id: '/_authed/parent/children/$childId/schedule'
      path: '/$childId/schedule'
      fullPath: '/parent/children/$childId/schedule'
      preLoaderRoute: typeof AuthedParentChildrenChildIdScheduleRouteImport
      parentRoute: typeof AuthedParentChildrenRoute
    }
    '/_authed/parent/children/$childId/report-cards': {
      id: '/_authed/parent/children/$childId/report-cards'
      path: '/$childId/report-cards'
      fullPath: '/parent/children/$childId/report-cards'
      preLoaderRoute: typeof AuthedParentChildrenChildIdReportCardsRouteImport
      parentRoute: typeof AuthedParentChildrenRoute
    }
    '/_authed/parent/children/$childId/grades': {
      id: '/_authed/parent/children/$childId/grades'
      path: '/$childId/grades'
      fullPath: '/parent/children/$childId/grades'
      preLoaderRoute: typeof AuthedParentChildrenChildIdGradesRouteImport
      parentRoute: typeof AuthedParentChildrenRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedAdminRouteRouteChildren {
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedParentChildrenRouteChildren {
  AuthedParentChildrenChildIdGradesRoute: typeof AuthedParentChildrenChildIdGradesRoute
  AuthedParentChildrenChildIdReportCardsRoute: typeof AuthedParentChildrenChildIdReportCardsRoute
  AuthedParentChildrenChildIdScheduleRoute: typeof AuthedParentChildrenChildIdScheduleRoute
}

const AuthedParentChildrenRouteChildren: AuthedParentChildrenRouteChildren = {
  AuthedParentChildrenChildIdGradesRoute:
    AuthedParentChildrenChildIdGradesRoute,
  AuthedParentChildrenChildIdReportCardsRoute:
    AuthedParentChildrenChildIdReportCardsRoute,
  AuthedParentChildrenChildIdScheduleRoute:
    AuthedParentChildrenChildIdScheduleRoute,
}

const AuthedParentChildrenRouteWithChildren =
  AuthedParentChildrenRoute._addFileChildren(AuthedParentChildrenRouteChildren)

interface AuthedParentRouteRouteChildren {
  AuthedParentChildrenRoute: typeof AuthedParentChildrenRouteWithChildren
  AuthedParentIndexRoute: typeof AuthedParentIndexRoute
}

const AuthedParentRouteRouteChildren: AuthedParentRouteRouteChildren = {
  AuthedParentChildrenRoute: AuthedParentChildrenRouteWithChildren,
  AuthedParentIndexRoute: AuthedParentIndexRoute,
}

const AuthedParentRouteRouteWithChildren =
  AuthedParentRouteRoute._addFileChildren(AuthedParentRouteRouteChildren)

interface AuthedSchoolAdminRouteRouteChildren {
  AuthedSchoolAdminIndexRoute: typeof AuthedSchoolAdminIndexRoute
  AuthedSchoolAdminReportsStatisticsRoute: typeof AuthedSchoolAdminReportsStatisticsRoute
  AuthedSchoolAdminStudentsStudentIdRoute: typeof AuthedSchoolAdminStudentsStudentIdRoute
  AuthedSchoolAdminStudentsAssignRoute: typeof AuthedSchoolAdminStudentsAssignRoute
  AuthedSchoolAdminStudentsPreRegisterRoute: typeof AuthedSchoolAdminStudentsPreRegisterRoute
  AuthedSchoolAdminYearsCreateRoute: typeof AuthedSchoolAdminYearsCreateRoute
  AuthedSchoolAdminAssessmentsIndexRoute: typeof AuthedSchoolAdminAssessmentsIndexRoute
  AuthedSchoolAdminClassroomsIndexRoute: typeof AuthedSchoolAdminClassroomsIndexRoute
  AuthedSchoolAdminFinanceIndexRoute: typeof AuthedSchoolAdminFinanceIndexRoute
  AuthedSchoolAdminParentsIndexRoute: typeof AuthedSchoolAdminParentsIndexRoute
  AuthedSchoolAdminReportsIndexRoute: typeof AuthedSchoolAdminReportsIndexRoute
  AuthedSchoolAdminScheduleIndexRoute: typeof AuthedSchoolAdminScheduleIndexRoute
  AuthedSchoolAdminStudentsIndexRoute: typeof AuthedSchoolAdminStudentsIndexRoute
  AuthedSchoolAdminTeachersIndexRoute: typeof AuthedSchoolAdminTeachersIndexRoute
  AuthedSchoolAdminYearsIndexRoute: typeof AuthedSchoolAdminYearsIndexRoute
  AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute: typeof AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute
  AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute: typeof AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute
  AuthedSchoolAdminReportsReportCardsCardIdRoute: typeof AuthedSchoolAdminReportsReportCardsCardIdRoute
  AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute: typeof AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute
  AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute: typeof AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute
  AuthedSchoolAdminTeachersTeacherIdWorkloadRoute: typeof AuthedSchoolAdminTeachersTeacherIdWorkloadRoute
  AuthedSchoolAdminYearsYearIdEditRoute: typeof AuthedSchoolAdminYearsYearIdEditRoute
  AuthedSchoolAdminReportsReportCardsIndexRoute: typeof AuthedSchoolAdminReportsReportCardsIndexRoute
  AuthedSchoolAdminReportsTranscriptsIndexRoute: typeof AuthedSchoolAdminReportsTranscriptsIndexRoute
  AuthedSchoolAdminScheduleTimeSlotsIndexRoute: typeof AuthedSchoolAdminScheduleTimeSlotsIndexRoute
  AuthedSchoolAdminYearsYearIdIndexRoute: typeof AuthedSchoolAdminYearsYearIdIndexRoute
}

const AuthedSchoolAdminRouteRouteChildren: AuthedSchoolAdminRouteRouteChildren =
  {
    AuthedSchoolAdminIndexRoute: AuthedSchoolAdminIndexRoute,
    AuthedSchoolAdminReportsStatisticsRoute:
      AuthedSchoolAdminReportsStatisticsRoute,
    AuthedSchoolAdminStudentsStudentIdRoute:
      AuthedSchoolAdminStudentsStudentIdRoute,
    AuthedSchoolAdminStudentsAssignRoute: AuthedSchoolAdminStudentsAssignRoute,
    AuthedSchoolAdminStudentsPreRegisterRoute:
      AuthedSchoolAdminStudentsPreRegisterRoute,
    AuthedSchoolAdminYearsCreateRoute: AuthedSchoolAdminYearsCreateRoute,
    AuthedSchoolAdminAssessmentsIndexRoute:
      AuthedSchoolAdminAssessmentsIndexRoute,
    AuthedSchoolAdminClassroomsIndexRoute:
      AuthedSchoolAdminClassroomsIndexRoute,
    AuthedSchoolAdminFinanceIndexRoute: AuthedSchoolAdminFinanceIndexRoute,
    AuthedSchoolAdminParentsIndexRoute: AuthedSchoolAdminParentsIndexRoute,
    AuthedSchoolAdminReportsIndexRoute: AuthedSchoolAdminReportsIndexRoute,
    AuthedSchoolAdminScheduleIndexRoute: AuthedSchoolAdminScheduleIndexRoute,
    AuthedSchoolAdminStudentsIndexRoute: AuthedSchoolAdminStudentsIndexRoute,
    AuthedSchoolAdminTeachersIndexRoute: AuthedSchoolAdminTeachersIndexRoute,
    AuthedSchoolAdminYearsIndexRoute: AuthedSchoolAdminYearsIndexRoute,
    AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute:
      AuthedSchoolAdminAssessmentsAssessmentIdSubjectsRoute,
    AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute:
      AuthedSchoolAdminAssessmentsAssessmentIdValidateRoute,
    AuthedSchoolAdminReportsReportCardsCardIdRoute:
      AuthedSchoolAdminReportsReportCardsCardIdRoute,
    AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute:
      AuthedSchoolAdminReportsTranscriptsTranscriptIdRoute,
    AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute:
      AuthedSchoolAdminTeachersTeacherIdAssignmentsRoute,
    AuthedSchoolAdminTeachersTeacherIdWorkloadRoute:
      AuthedSchoolAdminTeachersTeacherIdWorkloadRoute,
    AuthedSchoolAdminYearsYearIdEditRoute:
      AuthedSchoolAdminYearsYearIdEditRoute,
    AuthedSchoolAdminReportsReportCardsIndexRoute:
      AuthedSchoolAdminReportsReportCardsIndexRoute,
    AuthedSchoolAdminReportsTranscriptsIndexRoute:
      AuthedSchoolAdminReportsTranscriptsIndexRoute,
    AuthedSchoolAdminScheduleTimeSlotsIndexRoute:
      AuthedSchoolAdminScheduleTimeSlotsIndexRoute,
    AuthedSchoolAdminYearsYearIdIndexRoute:
      AuthedSchoolAdminYearsYearIdIndexRoute,
  }

const AuthedSchoolAdminRouteRouteWithChildren =
  AuthedSchoolAdminRouteRoute._addFileChildren(
    AuthedSchoolAdminRouteRouteChildren,
  )

interface AuthedStudentRouteRouteChildren {
  AuthedStudentGradesRoute: typeof AuthedStudentGradesRoute
  AuthedStudentReportCardsRoute: typeof AuthedStudentReportCardsRoute
  AuthedStudentScheduleRoute: typeof AuthedStudentScheduleRoute
  AuthedStudentIndexRoute: typeof AuthedStudentIndexRoute
}

const AuthedStudentRouteRouteChildren: AuthedStudentRouteRouteChildren = {
  AuthedStudentGradesRoute: AuthedStudentGradesRoute,
  AuthedStudentReportCardsRoute: AuthedStudentReportCardsRoute,
  AuthedStudentScheduleRoute: AuthedStudentScheduleRoute,
  AuthedStudentIndexRoute: AuthedStudentIndexRoute,
}

const AuthedStudentRouteRouteWithChildren =
  AuthedStudentRouteRoute._addFileChildren(AuthedStudentRouteRouteChildren)

interface AuthedSuperAdminRouteRouteChildren {
  AuthedSuperAdminAcademicYearsRoute: typeof AuthedSuperAdminAcademicYearsRoute
  AuthedSuperAdminAssessmentTypesRoute: typeof AuthedSuperAdminAssessmentTypesRoute
  AuthedSuperAdminConfigurationRoute: typeof AuthedSuperAdminConfigurationRoute
  AuthedSuperAdminCyclesRoute: typeof AuthedSuperAdminCyclesRoute
  AuthedSuperAdminGeographyRoute: typeof AuthedSuperAdminGeographyRoute
  AuthedSuperAdminLevelsRoute: typeof AuthedSuperAdminLevelsRoute
  AuthedSuperAdminPeriodsRoute: typeof AuthedSuperAdminPeriodsRoute
  AuthedSuperAdminReportsRoute: typeof AuthedSuperAdminReportsRoute
  AuthedSuperAdminSubjectsRoute: typeof AuthedSuperAdminSubjectsRoute
  AuthedSuperAdminThemeSettingsRoute: typeof AuthedSuperAdminThemeSettingsRoute
  AuthedSuperAdminTracksRoute: typeof AuthedSuperAdminTracksRoute
  AuthedSuperAdminUsersRoute: typeof AuthedSuperAdminUsersRoute
  AuthedSuperAdminIndexRoute: typeof AuthedSuperAdminIndexRoute
  AuthedSuperAdminSchoolsSchoolIdRoute: typeof AuthedSuperAdminSchoolsSchoolIdRoute
  AuthedSuperAdminSchoolsIndexRoute: typeof AuthedSuperAdminSchoolsIndexRoute
}

const AuthedSuperAdminRouteRouteChildren: AuthedSuperAdminRouteRouteChildren = {
  AuthedSuperAdminAcademicYearsRoute: AuthedSuperAdminAcademicYearsRoute,
  AuthedSuperAdminAssessmentTypesRoute: AuthedSuperAdminAssessmentTypesRoute,
  AuthedSuperAdminConfigurationRoute: AuthedSuperAdminConfigurationRoute,
  AuthedSuperAdminCyclesRoute: AuthedSuperAdminCyclesRoute,
  AuthedSuperAdminGeographyRoute: AuthedSuperAdminGeographyRoute,
  AuthedSuperAdminLevelsRoute: AuthedSuperAdminLevelsRoute,
  AuthedSuperAdminPeriodsRoute: AuthedSuperAdminPeriodsRoute,
  AuthedSuperAdminReportsRoute: AuthedSuperAdminReportsRoute,
  AuthedSuperAdminSubjectsRoute: AuthedSuperAdminSubjectsRoute,
  AuthedSuperAdminThemeSettingsRoute: AuthedSuperAdminThemeSettingsRoute,
  AuthedSuperAdminTracksRoute: AuthedSuperAdminTracksRoute,
  AuthedSuperAdminUsersRoute: AuthedSuperAdminUsersRoute,
  AuthedSuperAdminIndexRoute: AuthedSuperAdminIndexRoute,
  AuthedSuperAdminSchoolsSchoolIdRoute: AuthedSuperAdminSchoolsSchoolIdRoute,
  AuthedSuperAdminSchoolsIndexRoute: AuthedSuperAdminSchoolsIndexRoute,
}

const AuthedSuperAdminRouteRouteWithChildren =
  AuthedSuperAdminRouteRoute._addFileChildren(
    AuthedSuperAdminRouteRouteChildren,
  )

interface AuthedTeacherRouteRouteChildren {
  AuthedTeacherScheduleRoute: typeof AuthedTeacherScheduleRoute
  AuthedTeacherIndexRoute: typeof AuthedTeacherIndexRoute
  AuthedTeacherClassesClassIdRoute: typeof AuthedTeacherClassesClassIdRoute
  AuthedTeacherGradesClassIdRoute: typeof AuthedTeacherGradesClassIdRoute
  AuthedTeacherClassesIndexRoute: typeof AuthedTeacherClassesIndexRoute
  AuthedTeacherGradesIndexRoute: typeof AuthedTeacherGradesIndexRoute
}

const AuthedTeacherRouteRouteChildren: AuthedTeacherRouteRouteChildren = {
  AuthedTeacherScheduleRoute: AuthedTeacherScheduleRoute,
  AuthedTeacherIndexRoute: AuthedTeacherIndexRoute,
  AuthedTeacherClassesClassIdRoute: AuthedTeacherClassesClassIdRoute,
  AuthedTeacherGradesClassIdRoute: AuthedTeacherGradesClassIdRoute,
  AuthedTeacherClassesIndexRoute: AuthedTeacherClassesIndexRoute,
  AuthedTeacherGradesIndexRoute: AuthedTeacherGradesIndexRoute,
}

const AuthedTeacherRouteRouteWithChildren =
  AuthedTeacherRouteRoute._addFileChildren(AuthedTeacherRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedParentRouteRoute: typeof AuthedParentRouteRouteWithChildren
  AuthedSchoolAdminRouteRoute: typeof AuthedSchoolAdminRouteRouteWithChildren
  AuthedStudentRouteRoute: typeof AuthedStudentRouteRouteWithChildren
  AuthedSuperAdminRouteRoute: typeof AuthedSuperAdminRouteRouteWithChildren
  AuthedTeacherRouteRoute: typeof AuthedTeacherRouteRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSelectPortalRoute: typeof AuthedSelectPortalRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedParentRouteRoute: AuthedParentRouteRouteWithChildren,
  AuthedSchoolAdminRouteRoute: AuthedSchoolAdminRouteRouteWithChildren,
  AuthedStudentRouteRoute: AuthedStudentRouteRouteWithChildren,
  AuthedSuperAdminRouteRoute: AuthedSuperAdminRouteRouteWithChildren,
  AuthedTeacherRouteRoute: AuthedTeacherRouteRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSelectPortalRoute: AuthedSelectPortalRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
